### ISSUE TITLE
How to use single token for inference?

### ISSUE THREAD

**Issue by xiaoyangnihao** [CODEJIN/GST_Tacotron#5]

**Comment by CODEJIN** [comment]
Hi,

What is the single token you mean? Does you want to control the values of GST token directly, instead of reference mel? I have considered several methods, but with the current GST structure, it seems that the method of directly controlling each token is not appropriate. In the current model structure, it is difficult to assign only a specific style to a single GST token.

Thanks,

Heejo

**Comment by xiaoyangnihao** [comment]
> Hi,
> 
> What is the single token you mean? Does you want to control the values of GST token directly, instead of reference mel? I have considered several methods, but with the current GST structure, it seems that the method of directly controlling each token is not appropriate. In the current model structure, it is difficult to assign only a specific style to a single GST token.
> 
> Thanks,
> 
> Heejo

yeah, that's what I want to know correctly. Anyway, thanks for your replay.

**Comment by CODEJIN** [comment]
Okay. Sorry about I could not help.
